
CREATE TABLE CUSTOMER (
    CustomerID CHAR(5) PRIMARY KEY,
    FirstName VARCHAR2(20) NOT NULL,
    LastName VARCHAR2(20) NOT NULL,
    Phone CHAR(8)
);


CREATE TABLE ORDERS (
    OrderID CHAR(5) PRIMARY KEY,
    OrderDate DATE DEFAULT SYSDATE,
    CustomerID CHAR(5),
    FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID)
);

CREATE TABLE PRODUCT (
    ProductID CHAR(5) PRIMARY KEY,
    Description VARCHAR2(30) NOT NULL,
    Price NUMBER(7,2) NOT NULL,
    Category VARCHAR2(20)
);
CREATE TABLE ORDER_LINE (
    OrderID CHAR(5),
    ProductID CHAR(5),
    Quantity NUMBER(5) NOT NULL,
    PRIMARY KEY (OrderID, ProductID),
    FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID),
    FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID)
);

ALTER TABLE PRODUCT
ADD Category VARCHAR2(20);

ALTER TABLE ORDERS
ADD OrderDate DATE DEFAULT SYSDATE;
